'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {createApp}=require('../src/app');
async function req(base,path,opt={}){const r=await fetch(base+path,{...opt,headers:{'content-type':'application/json',...(opt.headers||{})}});return{status:r.status,body:await r.json(),headers:r.headers}}
async function fixture(){const app=createApp({dbPath:':memory:',adminEmail:'admin@example.invalid',adminPassword:'AdminPassword!123',assistMasterKey:Buffer.alloc(32,3).toString('base64')});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`,login=await req(base,'/api/login',{method:'POST',body:JSON.stringify({email:'admin@example.invalid',password:'AdminPassword!123'})});return{app,base,cookie:login.headers.get('set-cookie').split(';')[0],csrf:login.body.csrfToken,close:async()=>{await new Promise(r=>app.server.close(r));await app.close()}}}
const sales=(n,dealer='H704')=>({fullName:`Sales Uji ${n}`,email:`sales${n}@example.invalid`,phone:`08123456${String(n).padStart(4,'0')}`,salesCode:`S${String(n).padStart(4,'0')}`,dealerCode:dealer,password:'StrongPassword!123',status:'ACTIVE'});

test('Admin CRUD Sales memaksa role/dealer server-side, list semua status, dan CSRF',async()=>{const x=await fixture();try{const noCsrf=await req(x.base,'/api/admin/users',{method:'POST',headers:{cookie:x.cookie},body:JSON.stringify(sales(1))});assert.equal(noCsrf.status,403);const made=await req(x.base,'/api/admin/users',{method:'POST',headers:{cookie:x.cookie,'x-csrf-token':x.csrf},body:JSON.stringify({...sales(1,'H999'),role:'ADMIN',status:'SUSPENDED'})});assert.equal(made.status,201);assert.equal(made.body.user.role,'SALES');assert.equal(made.body.user.dealerCode,'H704');assert.equal(made.body.user.status,'ACTIVE');assert.equal(made.body.user.phone,sales(1).phone);const listed=await req(x.base,'/api/admin/users',{headers:{cookie:x.cookie}});assert.ok(listed.body.users.some(u=>u.id===made.body.user.id));const missing=await req(x.base,`/api/admin/users/${made.body.user.id}`,{method:'PATCH',headers:{cookie:x.cookie},body:'{}'});assert.equal(missing.status,403)}finally{await x.close()}});

test('edit Sales owner-scoped mengabaikan role/dealer, password opsional, dan mencabut semua sesi bila identitas sensitif berubah',async()=>{const x=await fixture();try{const u=x.app.services.users.create(sales(2)),login=await req(x.base,'/api/login',{method:'POST',body:JSON.stringify({email:u.email,password:sales(2).password})}),salesCookie=login.headers.get('set-cookie').split(';')[0];const edited=await req(x.base,`/api/admin/users/${u.id}`,{method:'PATCH',headers:{cookie:x.cookie,'x-csrf-token':x.csrf},body:JSON.stringify({fullName:'Sales Ubah Nama',email:'ubah@example.invalid',phone:'081277788899',salesCode:'UBAH01',password:'NewStrongPassword!456',dealerCode:'H999',role:'ADMIN',status:'ACTIVE'})});assert.equal(edited.status,200);assert.deepEqual({role:edited.body.user.role,dealer:edited.body.user.dealerCode},{role:'SALES',dealer:'H704'});assert.equal((await req(x.base,'/api/me',{headers:{cookie:salesCookie}})).status,401);assert.equal((await req(x.base,'/api/login',{method:'POST',body:JSON.stringify({email:'ubah@example.invalid',password:'NewStrongPassword!456'})})).status,200);const foreign=x.app.services.users.create(sales(3,'H999'));assert.equal((await req(x.base,`/api/admin/users/${foreign.id}`,{method:'PATCH',headers:{cookie:x.cookie,'x-csrf-token':x.csrf},body:JSON.stringify({fullName:'Tidak Boleh'})})).status,404)}finally{await x.close()}});

test('hapus Sales adalah soft-delete aman: login/sesi/worker diputus dan histori prospek serta audit dipertahankan',async()=>{const x=await fixture();try{const u=x.app.services.users.create(sales(4)),login=await req(x.base,'/api/login',{method:'POST',body:JSON.stringify({email:u.email,password:sales(4).password})}),salesCookie=login.headers.get('set-cookie').split(';')[0],t=new Date().toISOString();x.app.db.prepare('INSERT INTO prospects(id,owner_id,customer_name,phone,level,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run('history-1',u.id,'Customer Tetap','081399999999','LOW','DRAFT',t,t);const gone=await req(x.base,`/api/admin/users/${u.id}`,{method:'DELETE',headers:{cookie:x.cookie,'x-csrf-token':x.csrf},body:'{}'});assert.equal(gone.status,200);assert.equal(gone.body.user.status,'DELETED');assert.equal((await req(x.base,'/api/me',{headers:{cookie:salesCookie}})).status,401);assert.equal((await req(x.base,'/api/login',{method:'POST',body:JSON.stringify({email:u.email,password:sales(4).password})})).status,403);assert.equal(x.app.db.prepare('SELECT count(*) n FROM prospects WHERE owner_id=?').get(u.id).n,1);assert.ok(x.app.db.prepare("SELECT 1 FROM audit_logs WHERE action='USER_DELETE' AND target_id=?").get(u.id));const foreign=x.app.services.users.create(sales(5,'H999'));assert.equal((await req(x.base,`/api/admin/users/${foreign.id}`,{method:'DELETE',headers:{cookie:x.cookie,'x-csrf-token':x.csrf},body:'{}'})).status,404)}finally{await x.close()}});

test('Sales tidak dapat edit atau hapus akun melalui API Admin',async()=>{const x=await fixture();try{const u=x.app.services.users.create(sales(6)),login=await req(x.base,'/api/login',{method:'POST',body:JSON.stringify({email:u.email,password:sales(6).password})}),cookie=login.headers.get('set-cookie').split(';')[0],headers={cookie,'x-csrf-token':login.body.csrfToken};assert.equal((await req(x.base,`/api/admin/users/${u.id}`,{method:'PATCH',headers,body:'{}'})).status,403);assert.equal((await req(x.base,`/api/admin/users/${u.id}`,{method:'DELETE',headers,body:'{}'})).status,403)}finally{await x.close()}});

test('UI Admin menyediakan form tambah, edit, daftar semua status, dan konfirmasi hapus tanpa HTML sink',()=>{const fs=require('node:fs'),path=require('node:path'),html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8'),js=fs.readFileSync(path.join(__dirname,'../public/app.js'),'utf8');for(const id of ['adminUserCreateForm','adminUserEditForm','adminUserDeleteConfirm','userList'])assert.match(html,new RegExp(`id="${id}"`));assert.match(js,/\/api\/admin\/users/);assert.match(js,/method:'PATCH'/);assert.match(js,/method:'DELETE'/);assert.doesNotMatch(js,/\.innerHTML\s*=/)});
