'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createAssistRegionClient}=require('../src/assist-region-client');
const UUID={p:'11111111-1111-4111-8111-111111111111',d:'22222222-2222-4222-8222-222222222222',s:'33333333-3333-4333-8333-333333333333',v:'44444444-4444-4444-8444-444444444444'};

test('uses authoritative district operations and projects safe region fields',async()=>{const calls=[],transport=async x=>{calls.push(x);const root=x.query.match(/\{(getAll\w+)/)[1];return{data:{[root]:[{id:UUID[root.includes('Province')?'p':root.includes('Village')?'v':root.includes('SubDistrict')?'s':'d'],[root.includes('Province')?'provinceName':root.includes('SubDistrict')?'subDistrictName':root.includes('Village')?'villageName':'districtName']:'ACEH',[root.includes('Province')?'provinceCode':root.includes('SubDistrict')?'subDistrictCode':root.includes('Village')?'villageCode':'districtCode']:'11',postalCode:'23111'}]}}};const c=createAssistRegionClient({transport});assert.equal((await c.listProvinces('t'))[0].id,UUID.p);await c.listDistricts('t',UUID.p);await c.listSubDistricts('t',UUID.d);await c.listVillages('t',UUID.s);assert.match(calls[0].query,/getAllProvinceFromDistrict/);assert.match(calls[1].query,/getAllDistrictFromDistrict\(where:\{provinceId:\{eq:\$parentId\}\}/);assert.match(calls[2].query,/getAllSubDistrictFromDistrict\(where:\{districtId:\{eq:\$parentId\}\}/);assert.match(calls[3].query,/getAllVillageFromDistrict\(where:\{subDistrictId:\{eq:\$parentId\}\}/);assert.deepEqual(Object.keys((await c.listProvinces('t'))[0]).sort(),['code','id','name','postalCode'])});

test('cache is scoped by token and parent, bounded TTL, and invalid UUID fails closed',async()=>{let now=0,n=0;const c=createAssistRegionClient({now:()=>now,ttlMs:10,maxEntries:2,transport:async({query})=>{n++;const root=query.match(/\{(getAll\w+)/)[1];return{data:{[root]:[]}}}});await c.listDistricts('a',UUID.p);await c.listDistricts('a',UUID.p);assert.equal(n,1);await c.listDistricts('b',UUID.p);assert.equal(n,2);now=11;await c.listDistricts('a',UUID.p);assert.equal(n,3);await assert.rejects(()=>c.listDistricts('a','not-uuid'),e=>e.code==='REGION_ID_INVALID')});

test('rejects malformed upstream region response',async()=>{const c=createAssistRegionClient({transport:async()=>({data:{getAllProvinceFromDistrict:[{id:'bad',name:'X'}]}})});await assert.rejects(()=>c.listProvinces('t'),e=>e.code==='ASSIST_RESPONSE_INVALID')});

test('validateChain resolves authoritative names and rejects mismatched hierarchy',async()=>{const rows={getAllProvinceFromDistrict:[{id:UUID.p,provinceName:'ACEH',provinceCode:'11'}],getAllDistrictFromDistrict:[{id:UUID.d,districtName:'KOTA BANDA ACEH',districtCode:'1171'}],getAllSubDistrictFromDistrict:[{id:UUID.s,subDistrictName:'BAITURRAHMAN',subDistrictCode:'117101'}],getAllVillageFromDistrict:[{id:UUID.v,villageName:'PEUNITI',villageCode:'1171012001',postalCode:'23116'}]};const c=createAssistRegionClient({transport:async({query})=>{const root=query.match(/\{(getAll\w+)/)[1];return{data:{[root]:rows[root]}}}});const x=await c.validateChain('t',{provinceId:UUID.p,districtId:UUID.d,subDistrictId:UUID.s,villageId:UUID.v});assert.equal(x.village.name,'PEUNITI');assert.equal(x.postalCode,'23116');await assert.rejects(()=>c.validateChain('t',{provinceId:UUID.p,districtId:UUID.d,subDistrictId:UUID.s,villageId:UUID.p}),e=>e.code==='REGION_CHAIN_INVALID')});
