'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createAssistReadClient}=require('../src/assist-read-client');
const OWN='2bde62b4-3543-4cbc-a103-d68aab960b57',TOKEN=`x.${Buffer.from(JSON.stringify({sub:OWN})).toString('base64url')}.x`;

test('prospek dipaginasi penuh dan diproyeksikan aman',async()=>{
 const calls=[];const client=createAssistReadClient({transport:async({token,query,variables})=>{calls.push({token,query,variables});if(query.includes('PortalProspectFollowUps'))return{data:{getFollowUpHistoryFromCustomers:{nodes:[{customerProspectId:'p1',followUpDate:'2026-08-01',createdBy:OWN},{customerProspectId:'p2',followUpDate:'2026-08-02',createdBy:OWN}],pageInfo:{hasNextPage:false,endCursor:null}}}};return variables.after?{data:{getCustomerProspectFromCustomers:{nodes:[{id:'p2',prospectNumber:'H704-2',createdBy:OWN,name:'Budi',mobilePhoneNumber:'62812',prospectStatus:'HOT',created:'2026-08-02',iDNumber:'6401',address:'Alamat',description:'D',catalogueUnitColorDescription:'PCX'}],pageInfo:{hasNextPage:false,endCursor:null}}}}:{data:{getCustomerProspectFromCustomers:{nodes:[{id:'p1',prospectNumber:'H704-1',createdBy:OWN,name:'Ani',mobilePhoneNumber:'62811',prospectStatus:'MEDIUM',created:'2026-08-01'}],pageInfo:{hasNextPage:true,endCursor:'c1'}}}}}});const rows=await client.listProspects(TOKEN);assert.equal(rows.length,2);assert.equal(calls.length,3);assert.equal(calls[1].variables.after,'c1');assert.match(calls[2].query,/PortalProspectFollowUps/);assert.deepEqual(Object.keys(rows[0]).sort(),['address','createdAt','description','id','motor','name','nextFollowUpAt','nik','phone','prospectNumber','source','status'].sort());assert.equal(JSON.stringify(rows).includes('secret-token'),false);
});

test('prospek diurutkan terbaru dan memproyeksikan sumber resmi',async()=>{const client=createAssistReadClient({now:()=>new Date('2026-09-07T00:00:00Z'),transport:async({query})=>query.includes('PortalProspectFollowUps')?{data:{getFollowUpHistoryFromCustomers:{nodes:[{customerProspectId:'lama',followUpDate:'2026-09-01',createdBy:OWN},{customerProspectId:'baru',followUpDate:'2026-09-07',createdBy:OWN}],pageInfo:{hasNextPage:false,endCursor:null}}}}:({data:{getCustomerProspectFromCustomers:{nodes:[{id:'lama',prospectNumber:'H704-1',createdBy:OWN,created:'2026-09-01',sourceOfProspectHso:{description:'Website'}},{id:'baru',prospectNumber:'H704-2',createdBy:OWN,created:'2026-09-07',sourceOfProspectHso:{description:'Canvassing'}}],pageInfo:{hasNextPage:false,endCursor:null}}}})}),rows=await client.listProspects(TOKEN);assert.deepEqual(rows.map(x=>x.id),['baru','lama']);assert.equal(rows[0].source,'Canvassing')});

test('dedup telepon memakai filter server-side bounded, bukan membaca seluruh histori',async()=>{const calls=[],client=createAssistReadClient({transport:async x=>{calls.push(x);return{data:{getCustomerProspectFromCustomers:{nodes:[{id:'p1',prospectNumber:'H704-PRS-1',createdBy:OWN,mobilePhoneNumber:'628123456789',prospectStatus:'HOT'}],pageInfo:{hasNextPage:false,endCursor:null}}}}}}),rows=await client.findProspectsByPhone(TOKEN,'628123456789');assert.equal(rows.length,1);assert.equal(calls.length,1);assert.equal(calls[0].variables.phone,'628123456789');assert.equal(calls[0].variables.first,2);assert.match(calls[0].query,/where:\{mobilePhoneNumber:\{eq:\$phone\}\}/)});

test('dedup telepon cukup membuktikan minimal satu exact match walau histori lebih dari dua',async()=>{const client=createAssistReadClient({transport:async()=>({data:{getCustomerProspectFromCustomers:{nodes:[{id:'p1',prospectNumber:'H704-PRS-1',createdBy:OWN,mobilePhoneNumber:'628123456789',prospectStatus:'LOST'},{id:'p2',prospectNumber:'H704-PRS-2',createdBy:OWN,mobilePhoneNumber:'628123456789',prospectStatus:'LOST'}],pageInfo:{hasNextPage:true,endCursor:'more'}}}})});assert.equal((await client.findProspectsByPhone(TOKEN,'628123456789')).length,2)});
test('leads new dan ontrack dedup, new overdue dibuang',async()=>{
 const client=createAssistReadClient({transport:async({variables})=>({data:{leadsByAssignmentFromCrm:{nodes:[{activityLeadsAssignmentId:'a1',leadsId:'l1',customerName:'Ani',telephoneNo:'081',isOverdue:false,isOntrack:variables.ontrack},{activityLeadsAssignmentId:'a1',leadsId:'l1',customerName:'Ani Dupe',telephoneNo:'081',isOverdue:false,isOntrack:variables.ontrack},{activityLeadsAssignmentId:'a2',leadsId:'l2',customerName:'Expired',telephoneNo:'082',isOverdue:true,isOntrack:false}],pageInfo:{hasNextPage:false,endCursor:null}}}})});assert.equal((await client.listLeads('token','NEW')).length,1);assert.equal((await client.listLeads('token','ON_TRACK')).length,2);
});

test('GraphQL error disanitasi tanpa token atau detail upstream',async()=>{
 const client=createAssistReadClient({transport:async()=>({errors:[{message:'Bearer secret-token internal stack'}]})});await assert.rejects(()=>client.listProspects(TOKEN),e=>e.code==='ASSIST_REAUTH_REQUIRED'&&!e.message.includes('secret-token'));
});

test('pagination loop dan page limit ditolak',async()=>{
 const client=createAssistReadClient({maxPages:2,transport:async()=>({data:{getCustomerProspectFromCustomers:{nodes:[],pageInfo:{hasNextPage:true,endCursor:'same'}}}})});await assert.rejects(()=>client.listProspects(TOKEN),e=>e.code==='ASSIST_PAGINATION_INVALID');
});

test('deadline berlaku untuk keseluruhan pagination dan abort eksternal',async()=>{
 const transport=({signal})=>new Promise((resolve,reject)=>{const t=setTimeout(()=>resolve({data:{getCustomerProspectFromCustomers:{nodes:[],pageInfo:{hasNextPage:true,endCursor:String(Date.now())}}}}),80);signal.addEventListener('abort',()=>{clearTimeout(t);reject(Object.assign(new Error('aborted'),{name:'AbortError'}))},{once:true})}),client=createAssistReadClient({timeoutMs:100,transport});const started=Date.now();await assert.rejects(()=>client.listProspects(TOKEN),e=>e.code==='ASSIST_TIMEOUT');assert.ok(Date.now()-started<250);const c=new AbortController(),p=client.listProspects(TOKEN,{signal:c.signal});c.abort();await assert.rejects(()=>p,e=>e.code==='ASSIST_TIMEOUT')
});

test('query prospek membatasi dealer, owner JWT, dan histori 12 bulan di upstream',async()=>{let call;const client=createAssistReadClient({now:()=>new Date('2026-09-07T12:00:00Z'),transport:async x=>{call=x;return{data:{getCustomerProspectFromCustomers:{nodes:[],pageInfo:{hasNextPage:false,endCursor:null}}}}}});await client.listProspects(TOKEN);assert.match(call.query,/prospectNumber:\{startsWith:"H704-"\}/);assert.match(call.query,/createdBy:\{eq:\$owner\}/);assert.match(call.query,/created:\{gte:\$since\}/);assert.equal(call.variables.owner,OWN);assert.equal(call.variables.since,'2025-09-01T00:00:00.000Z')});

test('schema pageInfo ketat dan prospek dedup lintas halaman',async()=>{
 const bad=createAssistReadClient({transport:async()=>({data:{getCustomerProspectFromCustomers:{nodes:[],pageInfo:{hasNextPage:'yes',endCursor:null}}}})});await assert.rejects(()=>bad.listProspects(TOKEN),e=>e.code==='ASSIST_RESPONSE_INVALID');let n=0;const dedup=createAssistReadClient({transport:async({query})=>query.includes('PortalProspectFollowUps')?{data:{getFollowUpHistoryFromCustomers:{nodes:[{customerProspectId:'same',followUpDate:'2026-09-01',createdBy:OWN}],pageInfo:{hasNextPage:false,endCursor:null}}}}:({data:{getCustomerProspectFromCustomers:{nodes:[{id:'same',prospectNumber:'H704-PRS-1',createdBy:OWN}],pageInfo:n++?{hasNextPage:false,endCursor:null}:{hasNextPage:true,endCursor:'next'}}}})});assert.equal((await dedup.listProspects(TOKEN)).length,1)
});

test('list prospects memperkaya Next FU resmi dan memilih follow-up terbaru per customerProspectId',async()=>{
 const calls=[],client=createAssistReadClient({now:()=>new Date('2026-09-07T00:00:00Z'),transport:async x=>{calls.push(x);if(x.query.includes('PortalProspectFollowUps'))return{data:{getFollowUpHistoryFromCustomers:{nodes:[{customerProspectId:'p1',followUpDate:'2026-09-01T23:35:44.035Z',created:'2026-09-01T23:35:44.251Z',createdBy:OWN},{customerProspectId:'p1',followUpDate:'2026-08-01T00:00:00Z',created:'2026-08-01T00:00:00Z',createdBy:OWN}],pageInfo:{hasNextPage:false,endCursor:null}}}};return{data:{getCustomerProspectFromCustomers:{nodes:[{id:'p1',prospectNumber:'H704-PRS-2625146525',createdBy:OWN,name:'JAMILA',prospectStatus:'LOW',created:'2026-09-02T00:00:00Z'}],pageInfo:{hasNextPage:false,endCursor:null}}}}}});
 const rows=await client.listProspects(TOKEN);assert.equal(rows[0].nextFollowUpAt,'2026-09-01T23:35:44.035Z');assert.match(calls[1].query,/getFollowUpHistoryFromCustomers/);assert.deepEqual(calls[1].variables.ids,['p1']);
});

test('bulk not deal memakai filter server-side dan berhenti pada maxItems',async()=>{const calls=[],client=createAssistReadClient({pageSize:50,transport:async x=>{calls.push(x);const start=x.variables.after?50:0;return{data:{getCustomerProspectFromCustomers:{nodes:Array.from({length:50},(_,i)=>({id:`p${start+i}`,prospectNumber:`H704-${start+i}`,name:`Customer ${start+i}`,prospectStatus:'HOT',created:'2026-07-01T00:00:00.000Z',createdBy:OWN})),pageInfo:{hasNextPage:true,endCursor:x.variables.after?'c2':'c1'}}}}}}),rows=await client.listProspectsForNotDeal(TOKEN,{cutoffDate:'2026-08-01T00:00:00.000Z',maxAgeDays:30,maxItems:51});assert.equal(rows.length,51);assert.equal(calls.length,2);assert.deepEqual(calls[0].variables,{first:50,after:null});assert.match(calls[0].query,/prospectNumber:\{startsWith:"H704-"\}/);assert.match(calls[0].query,/prospectStatus:\{eq:PROSPECT\}/);assert.match(calls[0].query,/created:\{gte:"2026-07-02T00:00:00\.000Z",lte:"2026-08-01T00:00:00\.000Z"\}/);assert.doesNotMatch(calls.map(x=>x.query).join(''),/HOT_PROSPECT/);assert.match(calls[0].query,/nodes\{id prospectNumber name prospectStatus created\}/);assert.deepEqual(Object.keys(rows[0]).sort(),['createdAt','id','name','prospectNumber','status'].sort())});

test('find prospect by id memakai exact server filter bounded',async()=>{const calls=[],client=createAssistReadClient({transport:async x=>{calls.push(x);return{data:{getCustomerProspectFromCustomers:{nodes:[{id:'abc',prospectNumber:'H704-PRS-1',createdBy:OWN,prospectStatus:'HOT'}],pageInfo:{hasNextPage:false,endCursor:null}}}}}});assert.equal((await client.findProspectById(TOKEN,'abc')).id,'abc');assert.deepEqual(calls[0].variables,{first:1,id:'abc'});assert.match(calls[0].query,/\$id:UUID!/);assert.match(calls[0].query,/where:\{id:\{eq:\$id\}\}/);await assert.rejects(()=>client.findProspectById(TOKEN,'bad id'),e=>e.code==='PROSPECT_ID_INVALID')});

test('query prospek memakai urutan server terbaru yang stabil agar pagination tidak melewatkan data',async()=>{let query='';const client=createAssistReadClient({transport:async x=>{query=x.query;return{data:{getCustomerProspectFromCustomers:{nodes:[],pageInfo:{hasNextPage:false,endCursor:null}}}}}});await client.listProspects(TOKEN);assert.match(query,/order:\{created:DESC/)});


test('list prospects fail-closed berdasarkan subject token dan follow-up creator',async()=>{const payload=Buffer.from(JSON.stringify({sub:'2bde62b4-3543-4cbc-a103-d68aab960b57'})).toString('base64url'),token=`x.${payload}.x`,client=createAssistReadClient({now:()=>new Date('2026-09-07T00:00:00Z'),transport:async({query})=>query.includes('PortalProspectFollowUps')?{data:{getFollowUpHistoryFromCustomers:{nodes:[{id:'f1',customerProspectId:'p1',followUpDate:'2026-09-02T00:00:00Z',created:'2026-09-02T00:00:00Z',createdBy:'2bde62b4-3543-4cbc-a103-d68aab960b57'},{id:'f2',customerProspectId:'p2',followUpDate:'2026-09-02T00:00:00Z',created:'2026-09-02T00:00:00Z',createdBy:'04a8959d-f33c-4d37-aaf9-e7e711e0e85b'}],pageInfo:{hasNextPage:false,endCursor:null}}}}:{data:{getCustomerProspectFromCustomers:{nodes:[{id:'p1',prospectNumber:'H704-PRS-1',createdBy:OWN,name:'YUDHA',prospectStatus:'LOW',created:'2026-09-02T00:00:00Z'},{id:'p2',prospectNumber:'H704-PRS-2',createdBy:'04a8959d-f33c-4d37-aaf9-e7e711e0e85b',name:'RESTU',prospectStatus:'LOW',created:'2026-09-02T00:00:00Z'}],pageInfo:{hasNextPage:false,endCursor:null}}}}}),rows=await client.listProspects(token);assert.deepEqual(rows.map(x=>x.name),['YUDHA'])});

test('Lost memakai query status langsung dan histori 12 bulan tetap owner-scoped',async()=>{let first;const client=createAssistReadClient({now:()=>new Date('2026-09-08T00:00:00Z'),transport:async x=>{first||=(x);return x.query.includes('PortalProspectFollowUps')?{data:{getFollowUpHistoryFromCustomers:{nodes:[],pageInfo:{hasNextPage:false,endCursor:null}}}}:{data:{getCustomerProspectFromCustomers:{nodes:[{id:'own',prospectNumber:'H704-1',createdBy:OWN,prospectStatus:'LOST',created:'2026-08-30'},{id:'other',prospectNumber:'H704-2',createdBy:'04a8959d-f33c-4d37-aaf9-e7e711e0e85b',prospectStatus:'LOST',created:'2026-08-31'}],pageInfo:{hasNextPage:false,endCursor:null}}}}}}),rows=await client.listProspects(TOKEN,{status:'LOST'});assert.match(first.query,/prospectStatus:\{eq:LOST\}/);assert.match(first.query,/createdBy:\{eq:\$owner\}/);assert.equal(first.variables.since,'2025-09-01T00:00:00.000Z');assert.equal(first.variables.owner,OWN);assert.deepEqual(rows.map(x=>x.id),['own'])});


test('dashboard KPI memakai prospect bulan berjalan tanpa enrichment 12 bulan',async()=>{let captured;const c=createAssistReadClient({now:()=>new Date('2026-09-08T00:00:00Z'),transport:async x=>{captured=x;return{data:{getCustomerProspectFromCustomers:{nodes:[{id:'p1',prospectNumber:'H704-1',prospectStatus:'DEAL',created:'2026-09-02',createdBy:'11111111-1111-1111-1111-111111111111'},{id:'p2',prospectNumber:'H704-2',prospectStatus:'HOT',created:'2026-09-03',createdBy:'11111111-1111-1111-1111-111111111111'}],pageInfo:{hasNextPage:false,endCursor:null}}}}}}),jwt='eyJhbGciOiJub25lIn0.'+Buffer.from(JSON.stringify({sub:'11111111-1111-1111-1111-111111111111'})).toString('base64url')+'.';const rows=await c.getDashboardKpis(jwt);assert.equal(captured.variables.since,'2026-09-01T00:00:00.000Z');assert.deepEqual(rows,{prospects:1,deals:1})});
