'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {DatabaseSync}=require('node:sqlite');const {installBatchImportService}=require('../src/batch-import-service');
const ids={province:'00000000-0000-0000-0000-000000000001',district:'00000000-0000-0000-0000-000000000002',subDistrict:'00000000-0000-0000-0000-000000000003',village:'00000000-0000-0000-0000-000000000004'};function fx(regionClient){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT,status TEXT);INSERT INTO users VALUES('u','SALES','ACTIVE');CREATE TABLE prospects(id TEXT PRIMARY KEY,owner_id TEXT,customer_name TEXT,phone TEXT,level TEXT,motor TEXT,province TEXT,district TEXT,sub_district TEXT,village TEXT,nik TEXT,address TEXT,rt TEXT,rw TEXT,source_code TEXT,occupation TEXT,province_id TEXT,district_id TEXT,sub_district_id TEXT,village_id TEXT,postal_code TEXT,status TEXT,created_at TEXT,updated_at TEXT,UNIQUE(owner_id,phone));`);regionClient||={listProvinces:async()=>[{id:ids.province,name:'ACEH'}],listDistricts:async()=>[{id:ids.district,name:'KOTA BANDA ACEH'}],listSubDistricts:async()=>[{id:ids.subDistrict,name:'KECAMATAN BAITURRAHMAN'}],listVillages:async()=>[{id:ids.village,name:'KELURAHAN PEUNITI',postalCode:'23241'}]};return{db,s:installBatchImportService({db,regionClient,tokenFor:()=> 'token',now:()=> '2026-08-28T00:00:00Z'})}}
test('preview persisten idempotent, owner aktif, tidak insert draft',async()=>{const x=fx(),rows=[{name:'Aman Satu',phone:'628123456789',level:'LOW'}],a=await x.s.preview('u',rows,'batch-key-1'),b=await x.s.preview('u',rows,'batch-key-1');assert.equal(a.id,b.id);assert.equal(a.total,1);assert.equal(x.db.prepare('SELECT count(*) n FROM prospects').get().n,0)});
test('confirm insert atomik, dedup existing dilewati, cancel owner-only',async()=>{const x=fx(),rows=[{name:'Aman Satu',phone:'628123456789',level:'LOW'},{name:'Aman Dua',phone:'628123456780',level:'MEDIUM',motor:'LR1',province:'ACEH',district:'BANDA ACEH',subDistrict:'BAITURRAHMAN',village:'PEUNITI',address:'Jl',rt:'001',rw:'001'}],p=await x.s.preview('u',rows,'batch-key-2');x.db.prepare("INSERT INTO prospects(id,owner_id,customer_name,phone,level,motor,province,district,sub_district,village,nik,address,rt,rw,source_code,occupation,status,created_at,updated_at) VALUES('old','u','Old','628123456789','LOW',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'DRAFT','x','x')").run();const r=x.s.confirm('u',p.id);assert.equal(r.status,'SUCCEEDED');assert.equal(r.inserted,1);assert.equal(r.duplicates,1);assert.equal(x.db.prepare('SELECT count(*) n FROM prospects').get().n,2);assert.equal(x.db.prepare("SELECT input_origin FROM prospects WHERE phone='628123456780'").get().input_origin,'EXCEL');const q=await x.s.preview('u',[{name:'Tiga Aman',phone:'628123456781',level:'LOW'}],'batch-key-3');assert.equal(x.s.cancel('u',q.id).status,'CANCELLED')});
test('startup menandai RUNNING interrupted dan tidak insert otomatis',async()=>{const x=fx(),p=await x.s.preview('u',[{name:'Nama Aman',phone:'628123456789',level:'LOW'}],'batch-restart');x.db.prepare("UPDATE batch_import_operations SET status='RUNNING' WHERE id=?").run(p.id);x.s.startup();assert.equal(x.s.get('u',p.id).status,'FAILED');assert.equal(x.db.prepare('SELECT count(*) n FROM prospects').get().n,0)});
test('payload hash conflict, max 500, dan row invalid fail closed',async()=>{const x=fx();await assert.rejects(()=>x.s.preview('u',Array.from({length:501},(_,i)=>({name:`Nama ${i}`,phone:`62${String(81000000000+i)}`,level:'LOW'})),'batch-limit'),e=>e.code==='BATCH_ROW_LIMIT');await assert.rejects(()=>x.s.preview('u',[{name:'X',phone:'bad',level:'LOW'}],'batch-bad'),e=>e.code==='BATCH_ROW_INVALID');await x.s.preview('u',[{name:'Nama Aman',phone:'628123456789',level:'LOW'}],'batch-conflict');await assert.rejects(()=>x.s.preview('u',[{name:'Nama Beda',phone:'628123456780',level:'LOW'}],'batch-conflict'),e=>e.code==='IDEMPOTENCY_CONFLICT')});

test('ACEH authoritative names UUID postal',async()=>{const x=fx(),p=await x.s.preview('u',[{name:'Aceh Satu',phone:'628123456789',level:'MEDIUM',motor:'NE0B',address:'Jalan',province:'ACEH',district:'BANDA ACEH',subDistrict:'BAITURRAHMAN',village:'PEUNITI'}],'aceh-chain-1');x.s.confirm('u',p.id);assert.deepEqual({...x.db.prepare('SELECT province,district,sub_district,village,province_id,district_id,sub_district_id,village_id,postal_code FROM prospects').get()},{province:'ACEH',district:'KOTA BANDA ACEH',sub_district:'KECAMATAN BAITURRAHMAN',village:'KELURAHAN PEUNITI',province_id:ids.province,district_id:ids.district,sub_district_id:ids.subDistrict,village_id:ids.village,postal_code:'23241'})});
test('unknown dan ambiguous presisi',async()=>{for(const rows of [[],[{id:'a',name:'ACEH'},{id:'b',name:'PROVINSI ACEH'}]]){const x=fx({listProvinces:async()=>rows});await assert.rejects(()=>x.s.preview('u',[{name:'Aceh Satu',phone:'628123456789',level:'MEDIUM',motor:'N',address:'J',province:'ACEH',district:'BANDA ACEH',subDistrict:'BAITURRAHMAN',village:'PEUNITI'}],`region-${rows.length}-key`),e=>e.code===(rows.length?'BATCH_REGION_AMBIGUOUS':'BATCH_REGION_UNKNOWN')&&e.row===1&&e.field==='province')}});
