'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const {installProspectDeleteExcelDraftsService}=require('../src/prospect-delete-excel-drafts-service');
function fixture(){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT,status TEXT);CREATE TABLE prospects(id TEXT PRIMARY KEY,owner_id TEXT,status TEXT,input_origin TEXT,created_at TEXT);CREATE TABLE audit_logs(id TEXT,actor_user_id TEXT,action TEXT,target_id TEXT,result TEXT,created_at TEXT);INSERT INTO users VALUES('u1','SALES','ACTIVE'),('u2','SALES','ACTIVE');INSERT INTO prospects VALUES('excel','u1','DRAFT','EXCEL','1'),('manual','u1','DRAFT','MANUAL','2'),('sent','u1','SUBMITTED','EXCEL','3'),('foreign','u2','DRAFT','EXCEL','4');`);return{db,service:installProspectDeleteExcelDraftsService({db,now:()=> 't',audit:(actor,action,target,result)=>db.prepare('INSERT INTO audit_logs VALUES(?,?,?,?,?,?)').run('audit',actor,action,target,result,'t')})}}
test('preview counts only authenticated owner Excel drafts without deleting',()=>{const x=fixture(),op=x.service.preview('u1');assert.equal(op.count,1);assert.equal(x.db.prepare('SELECT count(*) n FROM prospects').get().n,4);assert.throws(()=>x.service.get('u2',op.id),e=>e.code==='NOT_FOUND')});
test('confirm transaction deletes only previewed owner Excel drafts and audits',()=>{const x=fixture(),op=x.service.preview('u1'),done=x.service.confirm('u1',op.id,op.count);assert.equal(done.deleted,1);assert.deepEqual(x.db.prepare('SELECT id FROM prospects ORDER BY id').all().map(x=>x.id),['foreign','manual','sent']);assert.ok(x.db.prepare("SELECT 1 FROM audit_logs WHERE actor_user_id='u1' AND action='PROSPECT_EXCEL_DRAFTS_DELETE_CONFIRM' AND result='SUCCESS'").get())});
test('confirm rejects stale count and leaves every prospect intact',()=>{const x=fixture(),op=x.service.preview('u1');x.db.prepare("INSERT INTO prospects VALUES('new','u1','DRAFT','EXCEL','5')").run();assert.throws(()=>x.service.confirm('u1',op.id,op.count),e=>e.code==='STALE_PREVIEW');assert.equal(x.db.prepare('SELECT count(*) n FROM prospects').get().n,5);assert.equal(x.db.prepare("SELECT count(*) n FROM audit_logs WHERE action='PROSPECT_EXCEL_DRAFTS_DELETE_CONFIRM'").get().n,0)});
test('confirm requires exact expected count from explicit confirmation',()=>{const x=fixture(),op=x.service.preview('u1');assert.throws(()=>x.service.confirm('u1',op.id),e=>e.code==='CONFIRMATION_REQUIRED');assert.equal(x.db.prepare('SELECT count(*) n FROM prospects').get().n,4)});
