'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {DatabaseSync}=require('node:sqlite');const {installProspectSubmitAllService}=require('../src/prospect-submit-all-service');
function fixture(){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT,status TEXT);CREATE TABLE prospects(id TEXT PRIMARY KEY,owner_id TEXT,status TEXT,created_at TEXT);INSERT INTO users VALUES('u1','SALES','ACTIVE'),('u2','SALES','ACTIVE');INSERT INTO prospects VALUES('a','u1','DRAFT','1'),('b','u1','SUBMITTED','2'),('c','u2','DRAFT','3');`);let previews=[],confirms=[];const submit={preview:async(u,p,k)=>{previews.push([u,p,k]);return{id:'child-'+p,status:'PREVIEW'}},confirm:async(u,id)=>{confirms.push(id);return{id,status:id.includes('a')?'UNKNOWN':'SUCCEEDED'}}};return{db,previews,confirms,service:installProspectSubmitAllService({db,submitService:submit,now:()=> 't'})}}
test('preview snapshots only owner drafts and performs no child/upstream work',async()=>{const x=fixture(),op=await x.service.preview('u1','bulk-key-123');assert.equal(op.total,1);assert.deepEqual(op.items.map(i=>i.prospectId),['a']);assert.equal(x.previews.length,0);assert.equal((await x.service.preview('u1','bulk-key-123')).id,op.id)});
test('same key conflicts when selected draft snapshot changes',async()=>{const x=fixture();await x.service.preview('u1','bulk-key-123');x.db.prepare("INSERT INTO prospects VALUES('d','u1','DRAFT','4')").run();await assert.rejects(()=>x.service.preview('u1','bulk-key-123'),e=>e.code==='IDEMPOTENCY_CONFLICT')});
test('preview gagal tertutup daripada diam-diam mengirim hanya sebagian draft',async()=>{const x=fixture();const limited=installProspectSubmitAllService({db:x.db,submitService:{preview(){throw Error('NO')},confirm(){throw Error('NO')}},maxItems:1});x.db.prepare("INSERT INTO prospects VALUES('d','u1','DRAFT','4')").run();await assert.rejects(()=>limited.preview('u1','bulk-limit-123'),e=>e.code==='SUBMIT_ALL_LIMIT')});
test('confirm executes sequential child preview-confirm and never retries UNKNOWN',async()=>{const x=fixture(),op=await x.service.preview('u1','bulk-key-123');const done=await x.service.confirm('u1',op.id);assert.equal(done.status,'COMPLETED');assert.equal(done.counts.UNKNOWN,1);assert.equal(x.previews.length,1);assert.equal(x.confirms.length,1);await x.service.confirm('u1',op.id);assert.equal(x.confirms.length,1)});
test('cancel only cancels preview pending items',async()=>{const x=fixture(),op=await x.service.preview('u1','bulk-key-123'),done=x.service.cancel('u1',op.id);assert.equal(done.status,'CANCELLED');assert.equal(done.counts.CANCELLED,1);assert.throws(()=>x.service.get('u2',op.id),e=>e.code==='NOT_FOUND')});
test('startup marks running orchestration UNKNOWN without child replay',async()=>{const x=fixture(),op=await x.service.preview('u1','bulk-key-123');x.db.prepare("UPDATE prospect_submit_all_operations SET status='RUNNING' WHERE id=?").run(op.id);await x.service.startup();assert.equal(x.service.get('u1',op.id).status,'UNKNOWN');assert.equal(x.confirms.length,0)});
/* RED verified before implementation: MODULE_NOT_FOUND */
