'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {DatabaseSync}=require('node:sqlite');
const {installProspectSubmitService}=require('../src/prospect-submit-service');
function fixture({level='LOW',read=[],create,update,claims={roles:JSON.stringify([{ConnectionType:'BusinessArea',ConnectionId:'channel-jwt',ConnectionName:'ASTRA MOTOR PENAJAM'}])}}={}){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT,status TEXT);CREATE TABLE prospects(id TEXT PRIMARY KEY,owner_id TEXT,customer_name TEXT,phone TEXT,level TEXT,motor TEXT,province TEXT,district TEXT,sub_district TEXT,village TEXT,nik TEXT,status TEXT,created_at TEXT,updated_at TEXT);`);db.prepare('INSERT INTO users VALUES(?,?,?)').run('u1','SALES','ACTIVE');db.prepare('INSERT INTO prospects VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('p1','u1','Budi','0812-3456-789',level,level==='LOW'?null:'LR1',level==='LOW'?null:'KALIMANTAN TIMUR',level==='LOW'?null:'PENAJAM PASER UTARA',level==='LOW'?null:'PENAJAM',level==='LOW'?null:'PENAJAM',level==='HOT'?'6401010101010001':null,'DRAFT','t','t');let calls=[];const jwt=`x.${Buffer.from(JSON.stringify(claims)).toString('base64url')}.x`;const service=installProspectSubmitService({db,master:require('../data/master-data.json'),tokenFor:()=>jwt,readClient:{listProspects:async()=>read},mutationClient:{createProspect:create|| (async(_t,p)=>{calls.push(['create',p]);return{id:'star1',prospectNumber:'H704-1',status:'PROSPECT'}}),updateProspectStatus:update|| (async(_t,p)=>{calls.push(['update',p]);return{id:'star1',status:p.toStatus}})},now:()=> '2026-08-28T00:00:00.000Z'});return{db,service,calls}}
test('preview persisten, owner-only, idempotent, dan tidak memanggil STAR create',async()=>{const x=fixture();const a=await x.service.preview('u1','p1','key-12345678'),b=await x.service.preview('u1','p1','key-12345678');assert.equal(a.id,b.id);assert.equal(a.status,'PREVIEW');assert.equal(x.calls.length,0);assert.throws(()=>x.service.preview('other','p1','other-key-1'),e=>e.code==='NOT_FOUND')});
test('confirm dedup telepon ASSIST sebelum create',async()=>{const x=fixture({read:[{id:'existing',phone:'628123456789',status:'PROSPECT'}]});const p=await x.service.preview('u1','p1','dedup-key-1');const r=await x.service.confirm('u1',p.id);assert.equal(r.status,'DUPLICATE');assert.equal(x.calls.length,0);assert.equal(x.db.prepare('SELECT status FROM prospects WHERE id=?').get('p1').status,'DRAFT')});
test('executor claim atomik, revalidasi token, channel dari JWT, dan create tepat sekali',async()=>{const x=fixture(),p=await x.service.preview('u1','p1','submit-key-1');const [a,b]=await Promise.all([x.service.confirm('u1',p.id),x.service.confirm('u1',p.id)]);assert.ok([a.status,b.status].every(s=>s==='SUCCEEDED'));assert.equal(x.calls.filter(c=>c[0]==='create').length,1);assert.equal(x.calls[0][1].channelId,'channel-jwt');assert.equal(x.db.prepare('SELECT status FROM prospects WHERE id=?').get('p1').status,'SUBMITTED')});
test('payload MEDIUM memakai UUID wilayah dan master data authoritative, bukan nilai browser',async()=>{const x=fixture({level:'MEDIUM'}),p=await x.service.preview('u1','p1','payload-key-1');assert.equal((await x.service.confirm('u1',p.id)).status,'SUCCEEDED');const body=x.calls.find(c=>c[0]==='create')[1];assert.match(body.provinceId,/^[0-9a-f-]{36}$/);assert.match(body.districtId,/^[0-9a-f-]{36}$/);assert.match(body.subDistrictId,/^[0-9a-f-]{36}$/);assert.match(body.villageId,/^[0-9a-f-]{36}$/);assert.equal(body.provinceName,'KALIMANTAN TIMUR');assert.equal(body.districtName,'PENAJAM PASER UTARA');assert.equal(body.subDistrictName,'PENAJAM');assert.equal(body.villageName,'PENAJAM')});

test('concurrent waiter bounded dan tidak mengeksekusi ulang claim RUNNING',async()=>{let release;const x=fixture({create:()=>new Promise(r=>{release=r})}),p=await x.service.preview('u1','p1','bounded-key-1'),first=x.service.confirm('u1',p.id);await new Promise(r=>setTimeout(r,5));const second=await x.service.confirm('u1',p.id,{waitMs:10});assert.equal(second.status,'RUNNING');release({id:'star1',prospectNumber:'H704-1',status:'PROSPECT'});assert.equal((await first).status,'SUCCEEDED')});

test('timeout create menjadi UNKNOWN dan tidak pernah blind retry',async()=>{let n=0;const x=fixture({create:async()=>{n++;throw Object.assign(new Error('timeout'),{code:'ASSIST_TIMEOUT'})}}),p=await x.service.preview('u1','p1','unknown-key-1');assert.equal((await x.service.confirm('u1',p.id)).status,'UNKNOWN');assert.equal((await x.service.run(p.id)).status,'UNKNOWN');assert.equal(n,1)});
test('MEDIUM create sukses lalu upgrade gagal tersimpan PARTIAL dan recovery hanya update',async()=>{let creates=0,updates=0;const x=fixture({level:'MEDIUM',create:async()=>{creates++;return{id:'star1',prospectNumber:'H704-1',status:'PROSPECT'}},update:async()=>{updates++;if(updates===1)throw Object.assign(new Error('rejected'),{code:'ASSIST_MUTATION_REJECTED'});return{id:'star1',status:'MEDIUM'}}}),p=await x.service.preview('u1','p1','partial-key-1');assert.equal((await x.service.confirm('u1',p.id)).status,'PARTIAL');assert.equal(x.db.prepare('SELECT status FROM prospects WHERE id=?').get('p1').status,'SUBMITTED_PARTIAL');assert.equal((await x.service.recover('u1',p.id)).status,'SUCCEEDED');assert.equal(creates,1);assert.equal(updates,2)});
test('recovery PARTIAL merevalidasi auth/abort sebelum update tanpa create ulang',async()=>{let tokenCalls=0,updates=0;const x=fixture({level:'MEDIUM',update:async()=>{updates++;throw Object.assign(new Error('reject'),{code:'ASSIST_MUTATION_REJECTED'})}}),p=await x.service.preview('u1','p1','recover-auth-1');assert.equal((await x.service.confirm('u1',p.id)).status,'PARTIAL');x.service.setTokenForForTest?.(()=>{tokenCalls++;throw Object.assign(new Error('revoked'),{code:'ASSIST_REAUTH_REQUIRED'})});const c=new AbortController();c.abort();assert.equal((await x.service.recover('u1',p.id,{signal:c.signal})).status,'PARTIAL');assert.equal(updates,1)});

test('lifecycle suspend per Sales membatalkan worker dan startup tidak replay RUNNING',async()=>{let release,creates=0;const x=fixture({create:async()=>{creates++;await new Promise(r=>{release=r});return{id:'late',prospectNumber:'late'}}}),p=await x.service.preview('u1','p1','lifecycle-key-1'),task=x.service.confirm('u1',p.id);await new Promise(r=>setTimeout(r,5));x.service.suspend('u1');release();const r=await task;assert.equal(r.status,'UNKNOWN');assert.equal(creates,1);x.db.prepare("UPDATE prospect_submit_operations SET status='RUNNING' WHERE id=?").run(p.id);await x.service.startup();assert.equal(x.service.status('u1',p.id).status,'UNKNOWN');assert.equal(creates,1)
});

test('abort sebelum POST tidak membuat prospek',async()=>{const x=fixture(),p=await x.service.preview('u1','p1','abort-key-123'),c=new AbortController();c.abort('SUSPENDED');assert.equal((await x.service.confirm('u1',p.id,{signal:c.signal})).status,'FAILED');assert.equal(x.calls.length,0)});
test('sales nonaktif ditolak pada preview, confirm, dan recovery',async()=>{const a=fixture();a.db.prepare("UPDATE users SET status='SUSPENDED' WHERE id='u1'").run();assert.throws(()=>a.service.preview('u1','p1','inactive-key'),e=>e.code==='NOT_FOUND');const b=fixture(),op=await b.service.preview('u1','p1','inactive-confirm');b.db.prepare("UPDATE users SET status='SUSPENDED' WHERE id='u1'").run();await assert.rejects(()=>b.service.confirm('u1',op.id),e=>e.code==='NOT_FOUND');const c=fixture({level:'MEDIUM',update:async()=>{throw Object.assign(Error('fail'),{code:'ASSIST_MUTATION_REJECTED'})}}),cop=await c.service.preview('u1','p1','inactive-recover');assert.equal((await c.service.confirm('u1',cop.id)).status,'PARTIAL');c.db.prepare("UPDATE users SET status='SUSPENDED' WHERE id='u1'").run();await assert.rejects(()=>c.service.recover('u1',cop.id),e=>e.code==='NOT_FOUND')});

test('preview simpan snapshot canonical dan confirm menolak draft berubah walau updated_at sama',async()=>{const x=fixture(),op=await x.service.preview('u1','p1','snapshot-key');const row=x.db.prepare('SELECT payload_json,payload_hash FROM prospect_submit_operations WHERE id=?').get(op.id);assert.equal(JSON.parse(row.payload_json).name,'Budi');assert.equal(row.payload_hash,require('node:crypto').createHash('sha256').update(row.payload_json).digest('hex'));x.db.prepare("UPDATE prospects SET customer_name='Budi Jahat' WHERE id='p1'").run();await assert.rejects(()=>x.service.confirm('u1',op.id),e=>e.code==='STALE_DRAFT');assert.equal(x.calls.length,0)});

test('migrasi tabel lama menambah payload_json tanpa merusak data',()=>{const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT,status TEXT);CREATE TABLE prospects(id TEXT PRIMARY KEY,owner_id TEXT,customer_name TEXT,phone TEXT,level TEXT,motor TEXT,province TEXT,district TEXT,sub_district TEXT,village TEXT,nik TEXT,status TEXT,created_at TEXT,updated_at TEXT);CREATE TABLE prospect_submit_operations(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,prospect_id TEXT NOT NULL,idempotency_key TEXT NOT NULL,payload_hash TEXT NOT NULL,status TEXT NOT NULL,star_id TEXT,star_number TEXT,error_code TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(user_id,idempotency_key));`);installProspectSubmitService({db,master:require('../data/master-data.json'),tokenFor:()=>'',readClient:{},mutationClient:{}});assert.ok(db.prepare("PRAGMA table_info(prospect_submit_operations)").all().some(x=>x.name==='payload_json'))});

test('migrasi duplicate legacy mengarsipkan konflik sebelum unique index',()=>{const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT,status TEXT);CREATE TABLE prospects(id TEXT PRIMARY KEY,owner_id TEXT);CREATE TABLE prospect_submit_operations(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,prospect_id TEXT NOT NULL,idempotency_key TEXT NOT NULL,payload_hash TEXT NOT NULL,payload_json TEXT,status TEXT NOT NULL,star_id TEXT,star_number TEXT,error_code TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);INSERT INTO prospect_submit_operations VALUES('old','u','p','key-old','h','{}','UNKNOWN',NULL,NULL,NULL,'2026-01-01','2026-01-01');INSERT INTO prospect_submit_operations VALUES('new','u','p','key-new','h','{}','PREVIEW',NULL,NULL,NULL,'2026-02-01','2026-02-01');`);installProspectSubmitService({db,master:require('../data/master-data.json'),tokenFor:()=>'',readClient:{},mutationClient:{}});assert.equal(db.prepare("SELECT id FROM prospect_submit_operations WHERE prospect_id='p'").get().id,'old');assert.equal(db.prepare("SELECT original_id FROM prospect_submit_operation_conflicts").get().original_id,'new');assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE type='index' AND name='idx_submit_one_prospect'").get())});

test('payload pakai source eksplisit serta channel id dan nama dari JWT',async()=>{const x=fixture(),op=await x.service.preview('u1','p1','claims-key');await x.service.confirm('u1',op.id);const body=x.calls[0][1];assert.equal(body.sourceOfProspectHsoId,'4cd4a103-4aa6-4d48-88e1-7bba6cb95d77');assert.equal(body.channelId,'channel-jwt');assert.equal(body.channelName,'ASTRA MOTOR PENAJAM')});

test('JWT production tanpa nama channel memakai nama dealer authoritative seperti bot',()=>{const x=fixture({claims:{roles:JSON.stringify([{ConnectionType:'BusinessArea',ConnectionId:'channel-jwt',Id:'role-id'}])}}),op=x.service.preview('u1','p1','production-claims-key'),body=JSON.parse(x.db.prepare('SELECT payload_json FROM prospect_submit_operations WHERE id=?').get(op.id).payload_json);assert.equal(body.channelId,'channel-jwt');assert.equal(body.channelName,'ASTRA MOTOR PENAJAM')});

test('telepon Indonesia invalid ditolak dan tidak false duplicate',()=>{const x=fixture();x.db.prepare("UPDATE prospects SET phone='00123' WHERE id='p1'").run();assert.throws(()=>x.service.preview('u1','p1','bad-phone-key'),e=>e.code==='PHONE_INVALID')});

test('dua recovery paralel hanya satu update STAR',async()=>{let updates=0,release;const x=fixture({level:'MEDIUM',update:async()=>{updates++;if(updates===1)throw Object.assign(Error('first'),{code:'ASSIST_MUTATION_REJECTED'});await new Promise(r=>{release=r});return{id:'star1'}}}),op=await x.service.preview('u1','p1','recover-race');assert.equal((await x.service.confirm('u1',op.id)).status,'PARTIAL');const a=x.service.recover('u1',op.id);await new Promise(r=>setTimeout(r,5));const b=await x.service.recover('u1',op.id);assert.equal(b.status,'RECOVERING');release();assert.equal((await a).status,'SUCCEEDED');assert.equal(updates,2)});

test('startup ubah RECOVERING ke PARTIAL tanpa create replay',async()=>{const x=fixture();const op=await x.service.preview('u1','p1','startup-recover');x.db.prepare("UPDATE prospect_submit_operations SET status='RECOVERING',star_id='star1' WHERE id=?").run(op.id);await x.service.startup();assert.equal(x.service.status('u1',op.id).status,'PARTIAL');assert.equal(x.calls.length,0)});

test('create sukses lalu persistence fault berakhir UNKNOWN tanpa retry',async()=>{let creates=0;const x=fixture({create:async()=>{creates++;x.db.exec(`CREATE TRIGGER fail_created BEFORE UPDATE OF star_id ON prospect_submit_operations BEGIN SELECT RAISE(FAIL,'disk fault'); END;`);return{id:'star1',prospectNumber:'N1',status:'PROSPECT'}}}),op=await x.service.preview('u1','p1','persist-fault');assert.equal((await x.service.confirm('u1',op.id)).status,'UNKNOWN');assert.equal((await x.service.run(op.id)).status,'UNKNOWN');assert.equal(creates,1)});

test.afterEach(()=>{});
