'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {DatabaseSync}=require('node:sqlite');const {installProspectSubmitAllService}=require('../src/prospect-submit-all-service');
function fixture(){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT,status TEXT);CREATE TABLE prospects(id TEXT PRIMARY KEY,owner_id TEXT,status TEXT,created_at TEXT,level TEXT DEFAULT 'LOW');INSERT INTO users VALUES('u1','SALES','ACTIVE'),('u2','SALES','ACTIVE');INSERT INTO prospects VALUES('a','u1','DRAFT','1','LOW'),('b','u1','SUBMITTED','2','LOW'),('c','u2','DRAFT','3','LOW');`);let previews=[],confirms=[];const submit={preview:async(u,p,k)=>{previews.push([u,p,k]);return{id:'child-'+p,status:'PREVIEW'}},confirm:async(u,id)=>{confirms.push(id);return{id,status:id.includes('a')?'UNKNOWN':'SUCCEEDED'}}};return{db,previews,confirms,service:installProspectSubmitAllService({db,submitService:submit,now:()=> 't'})}}
test('preview snapshots only owner drafts and performs no child/upstream work',async()=>{const x=fixture(),op=await x.service.preview('u1','bulk-key-123');assert.equal(op.total,1);assert.deepEqual(op.items.map(i=>i.prospectId),['a']);assert.equal(x.previews.length,0);assert.equal((await x.service.preview('u1','bulk-key-123')).id,op.id)});
test('same key conflicts when selected draft snapshot changes',async()=>{const x=fixture();await x.service.preview('u1','bulk-key-123');x.db.prepare("INSERT INTO prospects VALUES('d','u1','DRAFT','4','LOW')").run();await assert.rejects(()=>x.service.preview('u1','bulk-key-123'),e=>e.code==='IDEMPOTENCY_CONFLICT')});
test('preview gagal tertutup daripada diam-diam mengirim hanya sebagian draft',async()=>{const x=fixture();const limited=installProspectSubmitAllService({db:x.db,submitService:{preview(){throw Error('NO')},confirm(){throw Error('NO')}},maxItems:1});x.db.prepare("INSERT INTO prospects VALUES('d','u1','DRAFT','4','LOW')").run();await assert.rejects(()=>limited.preview('u1','bulk-limit-123'),e=>e.code==='SUBMIT_ALL_LIMIT')});
test('confirm executes sequential child preview-confirm and never retries UNKNOWN',async()=>{const x=fixture(),op=await x.service.preview('u1','bulk-key-123');const accepted=await x.service.confirm('u1',op.id);assert.equal(accepted.status,'RUNNING');const done=await x.service.run(op.id);assert.equal(done.status,'UNKNOWN');assert.equal(done.counts.UNKNOWN,1);assert.equal(x.previews.length,1);assert.equal(x.confirms.length,1);await x.service.confirm('u1',op.id);assert.equal(x.confirms.length,1)});
test('cancel only cancels preview pending items',async()=>{const x=fixture(),op=await x.service.preview('u1','bulk-key-123'),done=x.service.cancel('u1',op.id);assert.equal(done.status,'CANCELLED');assert.equal(done.counts.CANCELLED,1);assert.throws(()=>x.service.get('u2',op.id),e=>e.code==='NOT_FOUND')});
test('startup marks running orchestration UNKNOWN without child replay',async()=>{const x=fixture(),op=await x.service.preview('u1','bulk-key-123');x.db.prepare("UPDATE prospect_submit_all_operations SET status='RUNNING' WHERE id=?").run(op.id);await x.service.startup();assert.equal(x.service.get('u1',op.id).status,'UNKNOWN');assert.equal(x.confirms.length,0)});
/* RED verified before implementation: MODULE_NOT_FOUND */

test('confirm returns RUNNING immediately and run persists sequential progress with level delay except last',async()=>{const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT,status TEXT);CREATE TABLE prospects(id TEXT PRIMARY KEY,owner_id TEXT,status TEXT,created_at TEXT,level TEXT);INSERT INTO users VALUES('u1','SALES','ACTIVE');INSERT INTO prospects VALUES('a','u1','DRAFT','1','LOW'),('b','u1','DRAFT','2','HOT');`);let order=[],delays=[];const service=installProspectSubmitAllService({db,submitService:{preview:async(_u,p)=>({id:'c'+p,status:'PREVIEW'}),confirm:async(_u,id)=>{order.push(id);return{id,status:'SUCCEEDED'}}},delayMs:async(ms,_signal)=>delays.push(ms),random:()=>0,now:()=> 't'}),op=await service.preview('u1','background-key'),[first,second]=await Promise.all([service.confirm('u1',op.id),service.confirm('u1',op.id)]);assert.equal(first.status,'RUNNING');assert.equal(second.status,'RUNNING');assert.equal([first,second].filter(x=>x.startWorker).length,1);assert.equal(service.get('u1',op.id).processed,0);const done=await service.run(op.id);assert.deepEqual(order,['ca','cb']);assert.equal(done.processed,2);assert.equal(delays.length,1);assert.equal(delays[0],60000);assert.equal(done.estimatedRemainingMs,0)});
test('aggregate fail-closed dan estimasi mengikuti level',async()=>{const x=fixture();x.db.prepare("INSERT INTO prospects VALUES('d','u1','DRAFT','4','HOT')").run();const op=await x.service.preview('u1','aggregate-key');x.db.prepare("UPDATE prospect_submit_all_operations SET status='RUNNING' WHERE id=?").run(op.id);x.db.prepare("UPDATE prospect_submit_all_items SET status='UNKNOWN' WHERE bulk_id=? AND ordinal=0").run(op.id);x.db.prepare("UPDATE prospect_submit_all_items SET status='PARTIAL' WHERE bulk_id=? AND ordinal=1").run(op.id);const done=await x.service.run(op.id);assert.equal(done.status,'UNKNOWN');assert.equal(done.counts.UNKNOWN,1);assert.equal(done.counts.PARTIAL,1)});

test('cancel saat worker aktif tidak memproses item pending berikutnya',async()=>{const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT,status TEXT);CREATE TABLE prospects(id TEXT PRIMARY KEY,owner_id TEXT,status TEXT,created_at TEXT,level TEXT);INSERT INTO users VALUES('u1','SALES','ACTIVE');INSERT INTO prospects VALUES('a','u1','DRAFT','1','LOW'),('b','u1','DRAFT','2','HOT');`);let release,calls=[];const blocked=new Promise(r=>{release=r}),service=installProspectSubmitAllService({db,submitService:{preview:async(_u,p)=>{calls.push(p);if(p==='a')await blocked;return{id:'c'+p,status:'FAILED',errorCode:'TEST'}},confirm:async()=>{throw Error('must not')}}}),op=await service.preview('u1','cancel-race-key');await service.confirm('u1',op.id);const task=service.run(op.id);while(!calls.length)await new Promise(r=>setTimeout(r,1));service.cancel('u1',op.id);release();const done=await task;assert.deepEqual(calls,['a']);assert.equal(done.status,'CANCELLED');assert.equal(done.counts.CANCELLED,1)});

test('abort interrupts delay and cancels pending without replay',async()=>{const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT,status TEXT);CREATE TABLE prospects(id TEXT PRIMARY KEY,owner_id TEXT,status TEXT,created_at TEXT,level TEXT);INSERT INTO users VALUES('u1','SALES','ACTIVE');INSERT INTO prospects VALUES('a','u1','DRAFT','1','LOW'),('b','u1','DRAFT','2','HOT');`);let confirms=0;const service=installProspectSubmitAllService({db,submitService:{preview:async(_u,p)=>({id:'c'+p,status:'PREVIEW'}),confirm:async(_u,id)=>{confirms++;return{id,status:'SUCCEEDED'}}},delayMs:(_ms,signal)=>new Promise(resolve=>signal.addEventListener('abort',resolve,{once:true}))}),op=await service.preview('u1','abort-delay-key'),c=new AbortController();await service.confirm('u1',op.id);const task=service.run(op.id,{signal:c.signal});while(service.get('u1',op.id).processed<1)await new Promise(r=>setTimeout(r,1));c.abort();const done=await task;assert.equal(confirms,1);assert.equal(done.counts.CANCELLED,1)});
