'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {createApp}=require('../src/app');

async function request(base,path,options={}){const r=await fetch(base+path,{redirect:'manual',...options,headers:{'content-type':'application/json',...(options.headers||{})}}),text=await r.text();let body;try{body=JSON.parse(text)}catch{body=text}return{status:r.status,body,headers:r.headers}}
const password='StrongPassword!123';
let app,server,base,calls;
test.beforeEach(async()=>{calls=[];app=createApp({dbPath:':memory:',adminEmail:'admin@example.invalid',adminPassword:'AdminPassword!123',assistMasterKey:Buffer.alloc(32,7).toString('base64'),teamLeaderTokenProvider:async user=>{calls.push(['token',user.id,user.email]);return'secret-jwt'},teamLeaderDashboardClient:{getDashboard:async(token,period)=>{calls.push(['dashboard',token,period]);return{period,identity:{userId:'upstream-tl',role:'TEAMLEAD'},daily:[{day:1,prospect:9,target:440}],team:{teamLeaderId:'upstream-tl',teamLeaderName:'ABDUL RAHMADAN',totalSalesman:1,totalProspect:9,target:440,achievement:2.05,sales:[{id:'s1',name:'DESI',totalProspect:9,target:40,achievement:22.5}]}}}},assistActivityClient:{listActivities:async(token,options)=>{calls.push(['activities',token,options]);return[{assignmentActivityId:'assignment-1',activityId:'activity-1',type:'BTL',name:'Pameran Sepaku',staff:[{id:'s1',name:'DESI',lastClockIn:{kind:'duration',time:'08:00:00.000'},lastClockOut:null}]}]}},assistReadClient:{listProspects:async()=>[],listLeads:async()=>[]}});await app.ready;server=app.server;await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`});
test.afterEach(async()=>{await new Promise(r=>server.close(r));await app.close()});
async function login(user){const r=await request(base,'/api/login',{method:'POST',body:JSON.stringify({email:user.email,password})});return{...r,cookie:r.headers.get('set-cookie')?.split(';')[0]}}

test('TEAMLEAD aktif membaca dashboard dan Activity resmi via token provider tanpa token di respons',async()=>{const u=app.services.users.create({fullName:'Abdul Rahmadan',email:'abdul.rahmadan@hso.astra.co.id',phone:'081211110001',salesCode:'TLH704',dealerCode:'H704',password,role:'TEAMLEAD',status:'ACTIVE'}),l=await login(u),r=await request(base,'/api/team-leader/dashboard?month=9&year=2026&day=13',{headers:{cookie:l.cookie}});assert.equal(r.status,200);assert.equal(r.body.team.teamLeaderName,'ABDUL RAHMADAN');assert.equal(r.body.activities[0].name,'Pameran Sepaku');assert.deepEqual(calls.map(x=>x[0]),['token','dashboard','activities']);assert.equal(calls[1][1],'secret-jwt');assert.deepEqual({...calls[1][2],signal:undefined},{month:9,year:2026,day:13,signal:undefined});assert.equal(calls[2][1],'secret-jwt');assert.ok(calls[2][2].signal instanceof AbortSignal);assert.equal(JSON.stringify(r.body).includes('secret-jwt'),false);assert.ok(app.db.prepare("SELECT 1 FROM audit_logs WHERE actor_id=? AND action='TEAMLEAD_DASHBOARD_READ' AND result='SUCCESS'").get(u.id))});

test('TEAMLEAD memakai token vault portal sebelum broker dan dapat melihat status koneksi',async()=>{const u=app.services.users.create({fullName:'Abdul Vault',email:'tl-vault@example.invalid',phone:'081211110007',salesCode:'TLV001',dealerCode:'H704',password,role:'TEAMLEAD',status:'ACTIVE'});app.services.assist.store(u.id,{accessToken:'vault-jwt',displayName:'Abdul Vault',email:u.email,expiresAt:new Date(Date.now()+3600000).toISOString()});calls.length=0;const l=await login(u),connection=await request(base,'/api/assist/connection',{headers:{cookie:l.cookie}}),r=await request(base,'/api/team-leader/dashboard?month=9&year=2026&day=13',{headers:{cookie:l.cookie}});assert.equal(connection.status,200);assert.equal(connection.body.connection.status,'CONNECTED');assert.equal(r.status,200);assert.equal(calls.some(x=>x[0]==='token'),false);assert.equal(calls.find(x=>x[0]==='dashboard')[1],'vault-jwt')});

test('TEAMLEAD boleh memulai jalur login ASSIST sendiri',async()=>{const u=app.services.users.create({fullName:'Abdul Login',email:'tl-login@example.invalid',phone:'081211110008',salesCode:'TLL001',dealerCode:'H704',password,role:'TEAMLEAD',status:'ACTIVE'}),l=await login(u),r=await request(base,'/api/assist/login-jobs',{method:'POST',headers:{cookie:l.cookie,'x-csrf-token':l.body.csrfToken},body:JSON.stringify({username:'tl@example.invalid',password:'MicrosoftPassword!123'})});assert.notEqual(r.status,403);assert.equal(r.body.code,'LOGIN_UNAVAILABLE')});

test('Sales dan Admin ditolak dari endpoint TEAMLEAD',async()=>{for(const input of [{fullName:'Sales',email:'sales@example.invalid',phone:'081211110002',salesCode:'SAL001',role:'SALES'},{fullName:'Admin Dua',email:'admin2@example.invalid',phone:'081211110003',salesCode:'ADM002',role:'ADMIN'}]){const u=app.services.users.create({...input,dealerCode:'H704',password,status:'ACTIVE'}),l=await login(u),r=await request(base,'/api/team-leader/dashboard?month=9&year=2026&day=13',{headers:{cookie:l.cookie}});assert.equal(r.status,403);assert.equal(r.body.code,'FORBIDDEN')}assert.equal(calls.length,0)});

test('periode TEAMLEAD wajib integer bounded',async()=>{const u=app.services.users.create({fullName:'Abdul',email:'tl@example.invalid',phone:'081211110004',salesCode:'TL001',dealerCode:'H704',password,role:'TEAMLEAD',status:'ACTIVE'}),l=await login(u);for(const query of ['month=9x&year=2026&day=13','month=0&year=2026&day=13','month=9&year=2026&day=0']){const r=await request(base,`/api/team-leader/dashboard?${query}`,{headers:{cookie:l.cookie}});assert.equal(r.status,400);assert.equal(r.body.code,'INVALID_PERIOD')}assert.equal(calls.length,0)});

test('periode TEAMLEAD menolak tanggal kalender mustahil sebelum mengambil token',async()=>{const u=app.services.users.create({fullName:'Abdul',email:'tl-date@example.invalid',phone:'081211110006',salesCode:'TL003',dealerCode:'H704',password,role:'TEAMLEAD',status:'ACTIVE'}),l=await login(u),r=await request(base,'/api/team-leader/dashboard?month=2&year=2026&day=31',{headers:{cookie:l.cookie}});assert.equal(r.status,400);assert.equal(r.body.code,'INVALID_PERIOD');assert.equal(calls.length,0)});

test('kegagalan token provider tercatat tanpa detail secret',async()=>{app.services.teamLeader.setTokenProvider(async()=>{throw Object.assign(new Error('do not leak'),{code:'TEAMLEADER_TOKEN_UNAVAILABLE',status:503})});const u=app.services.users.create({fullName:'Abdul',email:'tl2@example.invalid',phone:'081211110005',salesCode:'TL002',dealerCode:'H704',password,role:'TEAMLEAD',status:'ACTIVE'}),l=await login(u),r=await request(base,'/api/team-leader/dashboard?month=9&year=2026&day=13',{headers:{cookie:l.cookie}});assert.equal(r.status,503);assert.equal(r.body.code,'TEAMLEADER_TOKEN_UNAVAILABLE');assert.ok(app.db.prepare("SELECT 1 FROM audit_logs WHERE actor_id=? AND action='TEAMLEAD_DASHBOARD_READ' AND result='FAILED'").get(u.id));assert.equal(JSON.stringify(r.body).includes('do not leak'),false)});
